### ISSUE TITLE
model page

### ISSUE THREAD

**Issue by rvadym** [atk4/book#14]
http://book.agiletoolkit.org/agiletoolkit-overview/model.html

* **The Dataset** - i think this part should be rewrited.
* **setSource - Primary Source** - require some examples. 
* **addCache - Caches** - same, require some examples. Much more :)
* **Model data and methods**. "In a typical ORM implementation, model data is stored in model properties while reserving all the property names beginning with underscore. Agile Toolkit stores model data as array in a single property called “data”." - add more low level explanation or stay on high level only. I think description set(), get() functions is more then enough at this point, most of the users will never ask you how it works behind the curtains.
* **class Model_User** doesn't have public $table property.
* "Please note that model is defined using PHP language and it’s always defined as a class." - i get confused with this phrase :) really :)
* ** you must define some fields** - how to define fields? Short example required here.
* **$m['name']='John';$m['daily_salary']=150;** - why this written in one line?
* ** Extend “User” model to create “Manager” model.** - example might be very useful here.
* **Loading and Saving models** - pretty good!
* **Relational Models (SQL)** - this is h3 element. Everything "described below" has h2 element for header. Not clear what exactly is "described below".

**Comment by romaninsh** [comment]
I'm closing this because Model is migrating into a new open-source project https://github.com/atk4/data
